# Generated by Django 6.0.1 on 2026-02-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='available_times',
        ),
        migrations.AddField(
            model_name='staff',
            name='available_day_end',
            field=models.CharField(default='Wed', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='available_day_start',
            field=models.CharField(default='Sat', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='available_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='available_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, default='default-doctor.jpg', null=True, upload_to='staff/'),
        ),
    ]
