# Generated by Django 6.0.1 on 2026-02-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_staff_available_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doctor',
            new_name='staff',
        ),
    ]
