# Generated by Django 6.0.1 on 2026-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_doctor_booking_staff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('staff', 'day', 'time'), name='unique_staff_booking_time'),
        ),
    ]
