# Generated by Django 6.0.1 on 2026-02-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_unique_staff_booking_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_staff_booking_time',
        ),
    ]
